cmi-compatible: false
luckperms-compatible: false
# Database type: mysql or mongodb
database:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    database: stats
    username: root
    password: ""
  mongodb:
    uri: mongodb://localhost:27017
    database: stats