name: {name}
version: {version}
main: me.kiratdewas.StatsPlugin
author: KiratDewas
api-version: 1.21
commands:
  stats:
    description: The main Stats command

libraries:
  - org.mongodb:mongodb-driver-sync:4.11.1
  - com.fasterxml.jackson.core:jackson-databind:2.17.1
  - com.mysql:mysql-connector-j:8.4.0
